name: marcenaria
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.4

  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  cupertino_icons: ^1.0.8

  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  animated_text_kit: ^4.2.2
  another_stepper: ^1.2.2
  custom_sliding_segmented_control: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.1
  analyzer: ^6.2.0
  build_runner:

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/login/icons/
    - assets/login/svgs/
    - assets/login/images/
    - assets/home/icons/
    - assets/covers/
    - assets/onboarding/
    - assets/profile/

  fonts:
    - family: Gotham Black
      fonts:
        - asset: assets/fonts/Gotham-Black.otf
    - family: Gotham Medium
      fonts:
        - asset: assets/fonts/Gotham-Medium.otf
    - family: Gotham Bold
      fonts:
        - asset: assets/fonts/Gotham-Bold.otf
    - family: Gotham Light
      fonts:
        - asset: assets/fonts/Gotham-Light.otf
    - family: Gotham Regular
      fonts:
        - asset: assets/fonts/Gotham-Book.otf
    - family: Gotham Regular Italic
      fonts:
        - asset: assets/fonts/Gotham-BookItalic.otf
    - family: Gotham Medium Italic
      fonts:
        - asset: assets/fonts/Gotham-MediumItalic.otf
    - family: Khula Regular
      fonts:
        - asset: assets/fonts/Khula-Regular.ttf
    - family: LoginIcons
      fonts:
        - asset: assets/login/icons/LoginIcons.ttf
    - family: NavigationIcons
      fonts:
        - asset: assets/home/icons/NavigationIcons.ttf
    - family: DrawerIcons
      fonts:
        - asset: assets/home/icons/DrawerIcons.ttf
    - family: ProfileIcons
      fonts:
        - asset: assets/profile/ProfileIcons.ttf
